### ISSUE TITLE
Migrate to klog

### ISSUE THREAD

**Issue by gyliu513** [IBM/operand-deployment-lifecycle-manager#138]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

We should use `klog` to mange the log of odlm to align with k8s eco-system.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

FYI @IBM/odlm-maintainers

**Comment by chenzhiwei** [comment]
do you know why kubebuilder does not use klog?

**Comment by gyliu513** [comment]
@chenzhiwei kubebuilder was created before klog, but it also have plan to migrate to klog.
