### ISSUE TITLE
remove state in OperandRequest

### ISSUE THREAD

**Issue by chenzhiwei** [IBM/operand-deployment-lifecycle-manager#142]
/kind feature

**Describe the solution you'd like**

Per the design, when users set a service in the OperanRequest, the ODLM should install the service and its dependencies.

This also needs all the services to add the `required` section in their CSV with the dependencies.

**Comment by horis233** [comment]
@chenzhiwei @DanielXLee When a dependent operator is deployed by the `required` section from an operator's CSV
