### ISSUE TITLE
Build operator registry image failed on OCP3.11

### ISSUE THREAD

**Issue by yahliu** [IBM/operand-deployment-lifecycle-manager#156]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Following the install doc https://github.com/IBM/operand-deployment-lifecycle-manager/blob/master/docs/install/install.md to run ODLM on ocp3.11
On step 1, hit below such error:
```
[ec2-user@suited-goldfish-ocp-master deploy]$ sudo docker build -t quay.io/opencloudio/operator-registry -f operator-registry.Dockerfile .
Sending build context to Docker daemon  72.7 kB
Step 1/10 : FROM quay.io/operator-framework/upstream-registry-builder as builder
Error parsing reference: "quay.io/operator-framework/upstream-registry-builder as builder" is not a valid repository/tag: invalid reference format
```
so skip step 1, continue to run step2, seem the `quay.io/opencloudio/operator-registry:latest` is too old.
```
[ec2-user@suited-goldfish-ocp-master ~]$ oc get CatalogSource -n olm
NAME                    DISPLAY               TYPE      PUBLISHER        AGE
opencloud-operators                           grpc                       3m
operatorhubio-catalog   Community Operators   grpc      OperatorHub.io   6m

[ec2-user@suited-goldfish-ocp-master ~]$ oc get packagemanifest -l catalog=opencloud-operators
NAME                CATALOG   AGE
meta-operator-app             4m45s
[ec2-user@suited-goldfish-ocp-master ~]$
```
**What did you expect to happen:**
Can be running ODLM on ocp3.11
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- ODLM version:
- Minikube/KIND/OCP version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by horis233** [comment]
@yahliu 

The error in the first step is an error in docker instead of ODLM Dockerfile. I think you need to upgrade your docker version.

**Comment by yahliu** [comment]
Thanks @horis233.  I can build the image after switch to docker version. but I can't push `quay.io/opencloudio/operator-registry`, seems I have no permission, so I push myself quay.io to test. but only ODLM in the source.
```
[cloudusr@guiding-swine-master ~]$ oc get packagemanifest -l catalog=opencloud-operators
NAME                                       CATALOG   AGE
operand-deployment-lifecycle-manager-app             53s
```
@gyliu513  so I heard from zhiwei Q1 release don't support OCP3.11.  I just double confirm if support it.

**Comment by gyliu513** [comment]
Low priority now.

**Comment by horis233** [comment]
We have deprecated `operator-registry`, closing the issue
