### ISSUE TITLE
Introduce `skipRange` to `OperandRegistry`

### ISSUE THREAD

**Issue by gyliu513** [IBM/operand-deployment-lifecycle-manager#188]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Please refer to https://github.com/operator-framework/operator-lifecycle-manager/issues/1287 for detail.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Here is a solution https://github.com/operator-framework/operator-lifecycle-manager/issues/1287#issuecomment-588571752

**Comment by gyliu513** [comment]
FYI @IBM/odlm-maintainers

**Comment by DanielXLee** [comment]
skipRange has added into csv
