### ISSUE TITLE
Definition for operand, operator and their relationship

### ISSUE THREAD

**Issue by nrchakradhar** [IBM/operand-deployment-lifecycle-manager#236]
/kind feature

**Describe the solution you'd like**
I went through the design document. The terms operator and operand are confusing in the context. Operator is generally a pattern comprising of CRDs and reconciliation logic.
In the same way what is an operand?
The mathematical definition seems to not apply intuitively here.
Can you please clarify?

What additional benefits will this provide and how the register and configs are used.
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by horis233** [comment]
@nrchakradhar 

Operands are the services and applications that Operators manage. 
For example, the MongoDB operator generates a MongoDB database.  the MongoDB database is the `operand` of the MongoDB `operator`.

The ODLM manages the deployment of the operands for OLM managed operators.  It provides a mechanism for dynamically deploying dependent (and optionally, shared) services in a prescriptive manner and allowing these deployments to interact when and where needed in a scoped fashion. You can understand ODLM as an extension of [operator-lifecycle-management](https://github.com/operator-framework/operator-lifecycle-manager).

> how the register and configs are used.
You can refer to the following documents:
- https://github.com/IBM/operand-deployment-lifecycle-manager/blob/master/docs/design/operand-deployment-lifecycle-manager.md#operandconfigs-spec
- https://github.com/IBM/operand-deployment-lifecycle-manager/blob/master/docs/design/operand-deployment-lifecycle-manager.md#operandregistry-spec

**Comment by nrchakradhar** [comment]
@horis233 thanks for sharing the information. You can close the ticket.
