### ISSUE TITLE
Reconcile OperandBindInfo when the OperandRegistry CR status changed 

### ISSUE THREAD

**Issue by DanielXLee** [IBM/operand-deployment-lifecycle-manager#314]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
When we create a new `OperandRequest`, it will update the `ReconcileRequests` into `OperandRegistry` CR status, but this change can not trigger `OperandBindInfo` reconcile, we need some investigation for how to watch CR status change.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by horis233** [comment]
@DanielXLee Could we let `OperandBindInfo` controller watch `OperandRegistry`
```
	// Watch for changes to primary resource OperandRegistry
	err = c.Watch(&source.Kind{Type: &operatorv1alpha1.OperandRegistry{}}, &handler.EnqueueRequestForObject{})
	if err != nil {
		return err
	}
```

**Comment by DanielXLee** [comment]
Done
