### ISSUE TITLE
BindInfo status cannot be set to Initialized

### ISSUE THREAD

**Issue by DanielXLee** [IBM/operand-deployment-lifecycle-manager#348]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

BindInfo status always empty, cannot be Initialized

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- ODLM version:
- Minikube/KIND/OCP version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by horis233** [comment]
Close it because #347 has been merged.
