### ISSUE TITLE
Upgrade operator-sdk to 0.16.0+

### ISSUE THREAD

**Issue by gyliu513** [IBM/operand-deployment-lifecycle-manager#369]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

Starting from 0.16.0, operator-sdk is going to support multiarch build https://github.com/operator-framework/operator-sdk/releases/tag/v0.16.0 , it is better to migrate to this version and leverage `operator-sdk` for build.

**Comment by gyliu513** [comment]
FYI @IBM/odlm-maintainers

**Comment by horis233** [comment]
@gyliu513 @chenzhiwei Is it still required? I have closed the old PR. I can open a new one for 3Q.

**Comment by gyliu513** [comment]
Already upgraded to 0.19.2
