### ISSUE TITLE
The update of the operandregistry status should not update operandrequest status

### ISSUE THREAD

**Issue by horis233** [IBM/operand-deployment-lifecycle-manager#405]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

When an operandrequest is updated (for example an operator is removed), it will trigger the update of the operandregistry. Then `operandregistry` will trigger all its `operandrequest` to reconcile, which will cost a long time to finish the reconcile. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by DanielXLee** [comment]
Using two controllers for one CR is not a good solution
Currently, our CR status updates are mutually updated, so I think we need a good solution, one controller only updates the owned CR.

**Comment by horis233** [comment]
Agree, I think we should avoid using operandconfig and operandregistry to update Operandrequest status to trigger updates as well. 

We need to build maps between operandconfig, operandregistry and operandrequest in the operandrequest controller.

**Comment by horis233** [comment]
We don't need this implementation, close the issue.
