### ISSUE TITLE
Updating sourceName in OperandRegistry does not trigger reconcile

### ISSUE THREAD

**Issue by gyliu513** [IBM/operand-deployment-lifecycle-manager#471]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

@chenzhiwei @DanielXLee @horis233 can you help check if the reconcile can handle the sourceName change in operandregistry?

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- ODLM version:
- Minikube/KIND/OCP version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by horis233** [comment]
@gyliu513 Currently, the ODLM only watches the channel changes in the Operandregistry. 

FYI @DanielXLee

**Comment by gyliu513** [comment]
Any plan to enable watch `sourceName`? Sometimes, the customer may want to change operator catalog to another.

**Comment by chenzhiwei** [comment]
in Q3 we will switch the source from CS to IBM Catalog, so this will be done in Q3.
