### ISSUE TITLE
IBM certification

### ISSUE THREAD

**Issue by horis233** [IBM/operand-deployment-lifecycle-manager#48]
https://playbook.cloudpaklab.ibm.com/operator-certification#4_Complete_IBM_certification
https://playbook.cloudpaklab.ibm.com/case-packaging
https://playbook.cloudpaklab.ibm.com/migrating-to-a-case-bundle#Conversion_from_a_Operator

**Comment by horis233** [comment]
I am not sure if our repo need to be refactored to CASE bundle. like the following instruction I generate:
<img width="1630" alt="Screen Shot 2020-02-10 at 4 13 25 PM" src="https://user-images.githubusercontent.com/33276414/74190428-5790e700-4c20-11ea-9837-8b3f0acf0231.png">

The only operator is transferred to bundle case is https://github.com/IBM/ibm-spectrum-scale-csi-operator
https://ibm-cloudplatform.slack.com/archives/C6A052PCL/p1581368862478800

**Comment by gyliu513** [comment]
@horis233 we can take this as low priority for Q1
