### ISSUE TITLE
Enable Hierarchical view for operators

### ISSUE THREAD

**Issue by gyliu513** [IBM/operand-deployment-lifecycle-manager#621]
Can we leverage https://github.com/ahmetb/kubectl-tree to enable the hierarchical view for operators managed by ODLM?

@IBM/odlm-maintainers ^^

**Comment by gyliu513** [comment]
@horis233 comments?

**Comment by horis233** [comment]
@gyliu513 

https://github.com/ahmetb/kubectl-tree bases on the owner reference to build the tree, but since operators created by OperandRequest may be in different namespaces, there is no owner reference between OperandRequest and operators. Thus, we can't use this CLI to list the resources/operators managed by ODLM.

We can deploy our own ODLM CLI to support that.

**Comment by gyliu513** [comment]
Thanks @horis233 , that's also my understanding. I think it is a great feature if we can enable end user can view the full topology of operators, can we enable this soon?

**Comment by horis233** [comment]
@gyliu513
I totally agree. 
I believe we can develop a script for it as a short-term solution. 
Then we can develop an ODLM CLI similar as https://github.com/ahmetb/kubectl-tree and https://github.com/operator-framework/kubectl-operator

**Comment by horis233** [comment]
@gyliu513 
I create a new repo for the ODLM CLI. https://github.com/IBM/kubectl-odlm

With initialized code, we can get a hierarchical view for an operandrequest
For example
```
➜  kubectl-odlm git:(main) ✗ ./bin/kubectl-odlm tree common-service
NAMESPACE            NAME                                                     
ibm-common-services  OperandRequest/common-service                            
ibm-common-services  ├─Subscription/ibm-iam-operator                          
ibm-common-services  │ └─ClusterServiceVersion/ibm-iam-operator.v3.9.1        
ibm-common-services  │   ├─OIDCClientWatcher/example-oidcclientwatcher        
ibm-common-services  │   ├─PolicyDecision/example-policydecision              
ibm-common-services  │   ├─Authentication/example-authentication              
ibm-common-services  │   ├─Pap/example-pap                                    
ibm-common-services  │   ├─PolicyController/policycontroller-deployment       
ibm-common-services  │   ├─SecretWatcher/secretwatcher-deployment             
ibm-common-services  │   ├─SecurityOnboarding/example-securityonboarding      
ibm-common-services  │   ├─OperandRequest/ibm-iam-request                     
ibm-common-services  │   └─OperandBindInfo/ibm-iam-bindinfo                   
ibm-common-services  └─Subscription/ibm-healthcheck-operator                  
ibm-common-services    └─ClusterServiceVersion/ibm-healthcheck-operator.v3.9.0
ibm-common-services      ├─HealthService/system-healthcheck-service           
ibm-common-services      ├─MustGatherConfig/must-gather-common-service-config 
ibm-common-services      ├─MustGatherConfig/must-gather-default-config        
ibm-common-services      └─MustGatherService/must-gather-service   
```

FYI @bitscuit @Daniel-Fan
