### ISSUE TITLE
Consider manual approve strategy

### ISSUE THREAD

**Issue by gyliu513** [IBM/operand-deployment-lifecycle-manager#627]
/kind feature

## Summary
The use of manual approval strategies for installplans in a cluster can impact the Bedrock installation experience which expects the use of automatic approval.

## Details
We must address the concern, potentially through documentation, that a cluster admin may encounter a situation where they have to work with manually approved installplan strategies. 

The user may not be familiar with OLM and these details, and it can have an impact on the current experience.

In order to account for this, we should inform the user of this caveat and provide additional information about this scenario and how to proceed if encountered. This should not be a critical/happy-path scenario and experience, but instead more of an edge case.

We can adjust our position if we understand the majority of administrators are favoring manual approval strategies. 

### Resources

- [Upstream OLM issue - stale](https://github.com/operator-framework/operator-lifecycle-manager/issues/1355)

@horis233

**Comment by horis233** [comment]
Yes, we noticed that OLM defect when users install CP4MCM with Manual approval. 

I agree we need to update the document to make users notify this defect when they decide to use manual approval.

Currently, ODLM supports manual install mode by editing the operandregistry
```
        operators:
        - name: ibm-licensing-operator
          namespace: placeholder
          channel: v3
          packageName: ibm-licensing-operator-app
          scope: public
          sourceName: opencloud-operators
          sourceNamespace: openshift-marketplace
          installPlanApproval: Manual  <---
```

Another thought about the manual approval is we can introduce a new CRD, which is used to approve installplans by OperandRequest or Namespace. Then end users don't need to approve installplans one by one.

**Comment by gyliu513** [comment]
> Another thought about the manual approval is we can introduce a new CRD, which is used to approve installplans by OperandRequest or Namespace. Then end users don't need to approve installplans one by one.

@horis233 I think we do not want to expose operator info to end user, so it would be great if we can have a parameter in opreq and manage all of the operators.

@taylormgeorge91 ^^

**Comment by Daniel-Fan** [comment]
@horis233 @gyliu513 

If the User set `intallPlanApproval: Manual` when installing the `ibm-common-service-operator`, then we could update `installPlanApproval: Manual` for all the operators in `common-service` `OperandRegistry`.

Does it sound good?

The question I have is do we need to consider the case, that the user set the `intallPlanApproval: Manual` when installing the `ibm-common-service-operator` at the first place. Then it wanna change to automatic approval, so the user will update `intallPlanApproval: Automatic` in the subscription of `ibm-common-service-operator`. In this situation, we will need to update `OperandRegistry` as well.

**Comment by gyliu513** [comment]
@Daniel-Fan @horis233 can we have the field of `intallPlanApproval` in the CR of  `ibm-common-service-operator`, if there are some changes for this field, then we need to update both `subscription` and `OperandRegistry`, does this make sense?

**Comment by Daniel-Fan** [comment]
I am ok with it.
It will make more clear to indicate the install strategy and we do need to support the case that user may change the approve strategy after the installation.

@horis233 any additional thoughts about it?

**Comment by horis233** [comment]
@gyliu513 @Daniel-Fan 

Yes, I agree with the field `intallPlanApproval`, we can implement it in the 2Q.

**Comment by Daniel-Fan** [comment]
Implementation suggestion:

Prereq:
1. the installation Approval Strateg of cs-operator, ODLM, namespace-scope operator will still be set in `Automatic` since they are not installed by ODLM.

Switch to Manual Approve:
Option1:
1. User update the `CommonService` CR with `intallPlanApproval: Manual`.
2. ODLM will watch the `CommonService` CR, if there is a change in `CommonService` CR which is in the same namespace with ODLM, and ODLM will requeue the `OperandRequest` that uses the `OperandRegistry` in that namespace scope to update the subscription and `OperandRegistry`.

Option2:
1. User update the `CommonService` CR with `intallPlanApproval: Manual`.
2. CS-operator reconcile the CR and pass a new env variable to ODLM subscription to indicate the `intallPlanApproval`.
3. ODLM will update the subscription and `OperandRegistry` in the corresponding namespace scope based on env variable.

**Comment by horis233** [comment]
@Daniel-Fan 

How about

1. User update the CommonService CR with `intallPlanApproval: Manual`.
2. CS-operator reconcile the CR and update OperandRegistry and the subscription of namespacescope operator.
3. ODLM will reconcile  OperandRequest to change operators to Manual approval mode

**Comment by Daniel-Fan** [comment]
@horis233 That sounds good, but I have a few questions.

> CS-operator reconcile the CR and update OperandRegistry and the subscription of namespacescope operator__

Does it means we only link the intallPlanApproval: Manual in CS CR with `common-service` OperandRegistry? Other `OperandRegistry` created by user will not be in the loop.
Also do we set the `namespace-scope operator` to manual approval as well?

> ODLM will reconcile OperandRequest to change operators to Manual approval mode
Same for `OperandRequest`, we only update the operators in `OperandRequest` with registry `common-service` in that namespace, right?

**Comment by horis233** [comment]
@Daniel-Fan 

Yes, correct. Common service operator shouldn't update the OperandRegistry and OperandRequest created by other users/operators.

**Comment by Daniel-Fan** [comment]
Implementation is in this PR, ready for reviewing.
https://github.com/IBM/ibm-common-service-operator/pull/485

**Comment by Daniel-Fan** [comment]
After installing the Common Service Operator, update the Common Service CR in the namespace where ODLM is installed.

The default approve strategy is `Automatic`, to change to `Manual`
```
apiVersion: operator.ibm.com/v3
kind: CommonService
metadata:
  name: common-service
  namespace: ibm-common-services
spec:
  installPlanApproval: Manual
  size: small
```
