### ISSUE TITLE
Support using default catalogsource in the OperandRegistry

### ISSUE THREAD

**Issue by horis233** [IBM/operand-deployment-lifecycle-manager#653]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by horis233** [comment]
### Stage 1

When catalogsource is not set in the OperandRegistry, ODLM will get the `packageManifest` in the target namespace of installing operator and get the catalogsource information from the status of the `packageManifest`. If the `packageManifest` can't be found then, return an error and requeue the reconciliation loop.

### Stage 2

In Stage 1, we can't handle the case there are multiple Catalogsource providing the same operator package.
`packageManifest` is a special k8s source. It customizes its special index in the OLM cache. https://github.com/operator-framework/operator-lifecycle-manager/blob/master/pkg/package-server/provider/registry.go#L71.
That causes in the same namespace, there could exist multiple `packageManifests` with the same name.

There are two questions, we need to consider:
1.  How to get all the `packageManifests` for an operator? 
2. How to decide using which catalogsource information from `packageManifests`?
 
_How to get all the `packageManifests` for an operator?_ 
**Option 1:** We can walk through all the `packageManifests` to get the `packageManifests` with the target package.
**Option 2:** We can build a special operator cache for `packageManifests` as OLM does.

_How to decide using which catalogsource information?_
**Option 1:** Following the OLM logic to check the catalogsource priority. concern: ODLM doesn't have priority into the `opennshift-marketplace` namespace.
 **Option 2:** Check the CSV version from the `packageManifests` and use the high version.

**Comment by Daniel-Fan** [comment]
> _How to get all the `packageManifests` for an operator?_ 
> **Option 1:** We can walk through all the `packageManifests` to get the `packageManifests` with the target package.
> **Option 2:** We can build a special operator cache for `packageManifests` as OLM does.

I think once there is a CatalogSource of operator is empty in `OperandRegistry`. we could consider it as the operator having multiple CatalogSources.
Then using the Option 2 could reduce the resource usage, although it will be complicated then option 1.

> _How to decide using which catalogsource information?_
> **Option 1:** Following the OLM logic to check the catalogsource priority. concern: ODLM doesn't have priority into the `opennshift-marketplace` namespace.
> **Option 2:** Check the CSV version from the `packageManifests` and use the high version.

I would prefer Option2.
In some cases, people may forget to delete the old CatalogSource after they apply the new CatalogSource with the higher version of operator. Option2 could help us eliminate damage under this situation.
Also choosing the higher version of operator is more intuitive.

**Comment by horis233** [comment]
Priority logic for stage 2.

- Find all PackageManifests that satisfy the Package.
- Filter out all PackageManifests that do not include the specified channel. This solves a multi-stream problem.
- Filter out all PackageManifests that ODLM does not have visiblity (no permissions). This solves a multi-tenant problem.
- Sort by namespace, prioritizing the OperandRegistry namespace, then lexigraphical
- Sort by name (unless we can figure out some labeling options or other suggestions by the OLM team)
